spring:
  application:
    name: eureka-service
  cloud:
    config:
      uri: http://${SPRING_CONFIG_URI:localhost:8888}

server:
  port: 8761

# configure eureka to single instance
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
